### ISSUE TITLE
Changing group and then viewing task crashes app

### ISSUE THREAD

**Issue by glindstedt** [douzifly/clear-todolist#11]
I've run into an issue where changing the group of a task can cause a crash.

Steps to reproduce:
- Select a task to edit it and change the group.
- In the task list it still shows the task as belonging to the old group.
- Try to select the task again for editing and the app crashes.

When the app is started again the task belongs to the new group and everything is back to normal. Please let me know if there's more information needed.

Tested on a Samsung Galaxy S4, Android version 4.4.2, Clear List version 1.5.1

**Comment by douzifly** [comment]
Hi, try the latest version on Google play, Version 1.5.3, already fixed this bug

**Comment by glindstedt** [comment]
Ok, thanks @douzifly! I installed it through F-Droid, it seems that the package is out of date there: [https://f-droid.org/wiki/page/douzifly.list](https://f-droid.org/wiki/page/douzifly.list).
