### ISSUE TITLE
Editing the date/time for a reminder does not suggest the previously set date/time

### ISSUE THREAD

**Issue by GitHorst** [douzifly/clear-todolist#14]
common scenario: you want to shift a reminder (e.g. far in the future) to one day later, same time.

what happens when you edit the reminder is that it suggests current date + current time. if you did not remember the previously set day, you have to go back (or it is lost, once you selected the date and then cancel during setting the time (=extra issue, actually)).

it would be better if the date and time it suggest first when you edit the reminder are the ones that were previously set.
(maybe there could be an extra button "today" to jump back to the current date in the calendar view? (like, e.g., in Mozilla Lightning))

**Comment by douzifly** [comment]
thanks for your advice
