### ISSUE TITLE
I can't reorder items

### ISSUE THREAD

**Issue by ic3m4n22** [douzifly/clear-todolist#17]
Hello,
first: thanks for making this app, it is very useful, i use it everyday as a to do list.

But since the version 1.5.x , I can't reorder items.
With 1.4.8, this feature worked great.

I've installed this app through F-Droid. I've Android 4.4.4

Thanks a lot!

**Comment by douzifly** [comment]
HI, When you choose 'all' group, the reorder functions is disabled..

**Comment by ic3m4n22** [comment]
Hello,
Ok, right! Thanks! my bad. :/ :p
How could we share this information? Maybe in the Readme file?
