### ISSUE TITLE
I cant clone project

### ISSUE THREAD

**Issue by tellfa** [douzifly/clear-todolist#7]
Hi, tnx for this project but i cant clone this project too Android Studio and request me Gradle home! 
how to fix it?
tnx

**Comment by douzifly** [comment]
try download the last AndroidStudio, eg. AndroidStudio1.5

**Comment by tellfa** [comment]
my Android Studio version is 1.5.1. it's last of version.
but i cant clone this project :(
please help me

**Comment by douzifly** [comment]
1, do you download this project to your hard disk?
2, show me the error message.

**Comment by tellfa** [comment]
1) no, i use project link : https://github.com/douzifly/clear-todolist , and clone this with VCS and Git
2) error image : 
![8](https://cloud.githubusercontent.com/assets/10583945/12711113/60e42fb8-c8d2-11e5-8d70-6dadf02ae1c9.jpg)

**Comment by douzifly** [comment]
try choose use default gradle wrapper, Android Studio will download environment automatic.

**Comment by tellfa** [comment]
where is default gradle wrapper ?

**Comment by douzifly** [comment]
try set gradle path like this:  /Applications/Android Studio.app/Contents/gradle/gradle-2.8
